import { Component, EventEmitter, Input, OnInit, Output, ViewChild } from '@angular/core';
import {select, Store} from '@ngrx/store';
import { setArtistStepIndexAction } from '../../store/merchant.action';
import { selectArtistStepIndex } from '../../store/merchant.selector';

@Component({
  selector: 'app-artist-hom',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class ArtistHomeComponent implements OnInit {

  @Input() data: any;
  @Output() onNextItem: EventEmitter<any> = new EventEmitter<any>();

  selectedArtworkStepIndex$ = this.store.pipe(select(selectArtistStepIndex));
  selectedArtworkStepIndex = 0;

  constructor(private store: Store) { }

  ngOnInit(): void {
    this.selectedArtworkStepIndex$.subscribe(data => this.selectedArtworkStepIndex = data);
  }

  onNext() {
    this.store.dispatch(setArtistStepIndexAction({stepIndex: this.selectedArtworkStepIndex + 1}));
    this.onNextItem.emit('');
  }

  onGoAutoGeneratedArtists(){
    this.store.dispatch(setArtistStepIndexAction({stepIndex: 1}));
    this.onNextItem.emit('');
  }

  onGoVettedArtists() {
    this.store.dispatch(setArtistStepIndexAction({stepIndex: 2}));
    this.onNextItem.emit('');
  }

}
